init_beeb_hacks: .macro
                jsr init_beeb_hacks_routine
                ldx #$ff
                txs
                lda #$7f
                pha
                lda #$ff
                pha
                .endm

init_beeb_hacks_routine:
                lda $202
                sta old_brkv+0
                lda $203
                sta old_brkv+1
                
                lda #<c64_style_brk_handler
                sta $202
                lda #>c64_style_brk_handler
                sta $203

                lda #<default_brk_routine
                sta $316
                lda #>default_brk_routine
                sta $317

                lda #0
                sta 2
                
                rts

default_brk_routine:
                pla
                tay
                pla
                tax
                pla
                jmp (old_brkv)

c64_style_brk_handler:
                pha
                txa
                pha
                tya
                pha
                tsx
                jmp ($0316)
                
print_char: .proc
                cmp #$80
                bcs done
                cmp #32
                bcs print
                cmp #13
                beq print
                cmp #10
                bne done
print:
                jsr $ffe3
done:
                rts
                .endproc
                
scan_keyboard:
                jsr $ffe0
                bcs exit
                cmp #0
                rts

exit:
                ldx #<star_basic
                ldy #>star_basic
                jmp $fff7

star_basic:
                .text "BASIC",13

load_file:
                lda old_brkv+0
                sta $202
                lda old_brkv+1
                sta $203
                
                ldy #0
copy_name_loop:
                lda ($bb),y
                sta name_buffer,y
                beq copy_name_done
                iny
                bne copy_name_loop
copy_name_done:
                lda #13
                sta name_buffer,y
                ldx #<name_buffer
                ldy #>name_buffer
                jmp $fff7


                .align 2
old_brkv:
                .fill 2
name_buffer:
                .fill 256
